version: "3"

services:
  postgres-db:
    build: ./postgres_db
    volumes:
    - ./postgres-db/pgdata/pgdata
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata
      - POSTGRES_DB=restapi_go


